#ifndef GUARD_CONSTANTS_O_POWERS_H
#define GUARD_CONSTANTS_O_POWERS_H

#define OPOWER_NONE 0
#define OPOWER_HATCHING 1
#define OPOWER_BARGAIN 2
#define OPOWER_PRIZE_MONEY 3
#define OPOWER_EXP_POINT 4
#define OPOWER_CAPTURE 5
#define OPOWER_ENCOUNTER 6
#define OPOWER_STEALTH 7
#define OPOWER_HP_RESTORING 8
#define OPOWER_PP_RESTORING 9
#define OPOWER_FULL_RECOVERY 10
#define OPOWER_BEFRIENDING 11
#define OPOWER_ATTACK 12
#define OPOWER_DEFENSE 13
#define OPOWER_SP_ATK 14
#define OPOWER_SP_DEF 15
#define OPOWER_SPEED 16
#define OPOWER_CRITICAL 17
#define OPOWER_ACCURACY 18

#define NUM_O_POWERS 19

#define OPOWER_LVL_LOCKED 0
#define OPOWER_LVL_1      1
#define OPOWER_LVL_2      2
#define OPOWER_LVL_3      3
#define OPOWER_LVL_S      4
#define OPOWER_LVL_MAX    5

#endif // GUARD_CONSTANTS_O_POWERS_H
