#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_DAD,
    SP_NAME_PLAYER,
    SP_PROF_BIRCH,
    SP_PROF_OAK,
    SP_NAME_BRENDAN,
    SP_NAME_MAY,
    SP_NAME_NORMAN,
    SP_NAME_WALLY,
    SP_NAME_ALMONDTWIST,
    SP_NAME_HAZELNUT,
    SP_NAME_MAXIE,
    SP_NAME_ARCHIE,
    SP_NAME_CAROLINE,
    SP_NAME_MAX,
    SP_NAME_CHARON,
    SP_NAME_ZENS,
    SP_NAME_JAY,
    SP_NAME_LOGAN,
    SP_NAME_DRAKE,
    SP_NAME_WALLACE,
    SP_NAME_STEVEN,
    SP_NAME_TABITHA,
    SP_NAME_COURTNEY,
    SP_NAME_SHELLY,
    SP_NAME_MATT,
    SP_NAME_UNKNOWN,
    SP_NAME_WISDOM,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
