with open("/home/charonchaos/PokemonShadowEmerald/src/data/outfit_tables.h", "r") as f:
    content = f.read()

replacements = [
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_MACH_BIKE  OBJ_EVENT_GFX_BRENDAN_MACH_BIKE", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_MACH_BIKE  OBJ_EVENT_GFX_LINK_RS_BRENDAN_MACH_BIKE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_ACRO_BIKE  OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_ACRO_BIKE  OBJ_EVENT_GFX_LINK_RS_BRENDAN_ACRO_BIKE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_SURFING    OBJ_EVENT_GFX_BRENDAN_SURFING", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_SURFING    OBJ_EVENT_GFX_LINK_RS_BRENDAN_SURFING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_UNDERWATER OBJ_EVENT_GFX_BRENDAN_UNDERWATER", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_UNDERWATER OBJ_EVENT_GFX_LINK_RS_BRENDAN_UNDERWATER"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_FIELD_MOVE OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_FIELD_MOVE OBJ_EVENT_GFX_LINK_RS_BRENDAN_FIELD_MOVE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_FISHING    OBJ_EVENT_GFX_BRENDAN_FISHING", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_FISHING    OBJ_EVENT_GFX_LINK_RS_BRENDAN_FISHING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_WATERING   OBJ_EVENT_GFX_BRENDAN_WATERING", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_WATERING   OBJ_EVENT_GFX_LINK_RS_BRENDAN_WATERING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_DECORATING OBJ_EVENT_GFX_BRENDAN_DECORATING", "#define OBJ_EVENT_GFX_OUTFIT_RS_BRENDAN_DECORATING OBJ_EVENT_GFX_LINK_RS_BRENDAN_DECORATING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_MACH_BIKE  OBJ_EVENT_GFX_MAY_MACH_BIKE", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_MACH_BIKE  OBJ_EVENT_GFX_LINK_RS_MAY_MACH_BIKE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_ACRO_BIKE  OBJ_EVENT_GFX_MAY_ACRO_BIKE", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_ACRO_BIKE  OBJ_EVENT_GFX_LINK_RS_MAY_ACRO_BIKE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_SURFING    OBJ_EVENT_GFX_MAY_SURFING", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_SURFING    OBJ_EVENT_GFX_LINK_RS_MAY_SURFING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_UNDERWATER OBJ_EVENT_GFX_MAY_UNDERWATER", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_UNDERWATER OBJ_EVENT_GFX_LINK_RS_MAY_UNDERWATER"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_FIELD_MOVE OBJ_EVENT_GFX_MAY_FIELD_MOVE", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_FIELD_MOVE OBJ_EVENT_GFX_LINK_RS_MAY_FIELD_MOVE"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_FISHING    OBJ_EVENT_GFX_MAY_FISHING", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_FISHING    OBJ_EVENT_GFX_LINK_RS_MAY_FISHING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_WATERING   OBJ_EVENT_GFX_MAY_WATERING", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_WATERING   OBJ_EVENT_GFX_LINK_RS_MAY_WATERING"),
    ("#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_DECORATING OBJ_EVENT_GFX_MAY_DECORATING", "#define OBJ_EVENT_GFX_OUTFIT_RS_MAY_DECORATING OBJ_EVENT_GFX_LINK_RS_MAY_DECORATING"),
]

for old, new in replacements:
    content = content.replace(old, new)

with open("/home/charonchaos/PokemonShadowEmerald/src/data/outfit_tables.h", "w") as f:
    f.write(content)
